export const mockWeatherData = {
  location: {
    name: "Lucknow",
    region: "Uttar Pradesh",
    country: "India",
    lat: 26.85,
    lon: 80.92,
    tz_id: "Asia/Kolkata",
    localtime_epoch: 1627896600,
    localtime: "2023-08-02 15:30"
  },
  current: {
    last_updated_epoch: 1627896000,
    last_updated: "2023-08-02 15:00",
    temp_c: 32.0,
    temp_f: 89.6,
    is_day: 1,
    condition: {
      text: "Partly cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
      code: 1003
    },
    wind_kph: 15.1,
    wind_mph: 9.4,
    wind_degree: 290,
    wind_dir: "WNW",
    pressure_mb: 1008.0,
    pressure_in: 29.77,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 66,
    cloud: 25,
    feelslike_c: 34.8,
    feelslike_f: 94.6,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 7.0,
    gust_mph: 10.5,
    gust_kph: 16.9
  },
  forecast: {
    forecastday: [
      {
        date: "2023-08-02",
        date_epoch: 1627862400,
        day: {
          maxtemp_c: 34.5,
          maxtemp_f: 94.1,
          mintemp_c: 26.8,
          mintemp_f: 80.2,
          avgtemp_c: 30.4,
          avgtemp_f: 86.7,
          maxwind_mph: 11.0,
          maxwind_kph: 17.6,
          totalprecip_mm: 0.5,
          totalprecip_in: 0.02,
          totalsnow_cm: 0.0,
          avgvis_km: 9.0,
          avgvis_miles: 5.0,
          avghumidity: 71,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 69,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063
          },
          uv: 7.0
        },
        astro: {
          sunrise: "05:40 AM",
          sunset: "07:02 PM",
          moonrise: "12:48 AM",
          moonset: "02:36 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "34"
        },
        hour: [
          {
            time_epoch: 1627851600,
            time: "2023-08-02 00:00",
            temp_c: 27.2,
            temp_f: 81.0,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 260,
            wind_dir: "W",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 84,
            cloud: 0,
            feelslike_c: 30.5,
            feelslike_f: 86.9,
            windchill_c: 27.2,
            windchill_f: 81.0,
            heatindex_c: 30.5,
            heatindex_f: 86.9,
            dewpoint_c: 24.1,
            dewpoint_f: 75.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 1.0
          },
          {
            time_epoch: 1627855200,
            time: "2023-08-02 01:00",
            temp_c: 27.0,
            temp_f: 80.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 268,
            wind_dir: "W",
            pressure_mb: 1010.0,
            pressure_in: 29.81,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 0,
            feelslike_c: 30.2,
            feelslike_f: 86.4,
            windchill_c: 27.0,
            windchill_f: 80.6,
            heatindex_c: 30.2,
            heatindex_f: 86.4,
            dewpoint_c: 24.2,
            dewpoint_f: 75.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 1.0
          },
          {
            time_epoch: 1627858800,
            time: "2023-08-02 02:00",
            temp_c: 26.8,
            temp_f: 80.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 275,
            wind_dir: "W",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 86,
            cloud: 0,
            feelslike_c: 29.7,
            feelslike_f: 85.5,
            windchill_c: 26.8,
            windchill_f: 80.2,
            heatindex_c: 29.7,
            heatindex_f: 85.5,
            dewpoint_c: 24.2,
            dewpoint_f: 75.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1.0
          },
          {
            time_epoch: 1627862400,
            time: "2023-08-02 03:00",
            temp_c: 26.9,
            temp_f: 80.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 271,
            wind_dir: "W",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 0,
            feelslike_c: 29.9,
            feelslike_f: 85.8,
            windchill_c: 26.9,
            windchill_f: 80.4,
            heatindex_c: 29.9,
            heatindex_f: 85.8,
            dewpoint_c: 24.1,
            dewpoint_f: 75.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1.0
          },
          {
            time_epoch: 1627866000,
            time: "2023-08-02 04:00",
            temp_c: 26.8,
            temp_f: 80.2,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 266,
            wind_dir: "W",
            pressure_mb: 1010.0,
            pressure_in: 29.81,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 33,
            feelslike_c: 29.5,
            feelslike_f: 85.1,
            windchill_c: 26.8,
            windchill_f: 80.2,
            heatindex_c: 29.5,
            heatindex_f: 85.1,
            dewpoint_c: 23.9,
            dewpoint_f: 75.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1.0
          },
          {
            time_epoch: 1627869600,
            time: "2023-08-02 05:00",
            temp_c: 26.6,
            temp_f: 79.9,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 260,
            wind_dir: "W",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 84,
            cloud: 67,
            feelslike_c: 29.1,
            feelslike_f: 84.4,
            windchill_c: 26.6,
            windchill_f: 79.9,
            heatindex_c: 29.1,
            heatindex_f: 84.4,
            dewpoint_c: 23.6,
            dewpoint_f: 74.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1.0
          },
          {
            time_epoch: 1627873200,
            time: "2023-08-02 06:00",
            temp_c: 27.4,
            temp_f: 81.3,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 280,
            wind_dir: "W",
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 77,
            cloud: 100,
            feelslike_c: 29.7,
            feelslike_f: 85.5,
            windchill_c: 27.4,
            windchill_f: 81.3,
            heatindex_c: 29.7,
            heatindex_f: 85.5,
            dewpoint_c: 23.0,
            dewpoint_f: 73.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 6.0
          },
          {
            time_epoch: 1627876800,
            time: "2023-08-02 07:00",
            temp_c: 28.3,
            temp_f: 82.9,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 301,
            wind_dir: "WNW",
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 100,
            feelslike_c: 30.2,
            feelslike_f: 86.4,
            windchill_c: 28.3,
            windchill_f: 82.9,
            heatindex_c: 30.2,
            heatindex_f: 86.4,
            dewpoint_c: 22.4,
            dewpoint_f: 72.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 7.0
          },
          {
            time_epoch: 1627880400,
            time: "2023-08-02 08:00",
            temp_c: 29.2,
            temp_f: 84.6,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 321,
            wind_dir: "NW",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 100,
            feelslike_c: 30.8,
            feelslike_f: 87.4,
            windchill_c: 29.2,
            windchill_f: 84.6,
            heatindex_c: 30.8,
            heatindex_f: 87.4,
            dewpoint_c: 21.7,
            dewpoint_f: 71.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 7.0
          },
          {
            time_epoch: 1627884000,
            time: "2023-08-02 09:00",
            temp_c: 30.1,
            temp_f: 86.2,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 342,
            wind_dir: "NNW",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 100,
            feelslike_c: 31.3,
            feelslike_f: 88.3,
            windchill_c: 30.1,
            windchill_f: 86.2,
            heatindex_c: 31.3,
            heatindex_f: 88.3,
            dewpoint_c: 21.0,
            dewpoint_f: 69.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 7.0
          },
          {
            time_epoch: 1627887600,
            time: "2023-08-02 10:00",
            temp_c: 31.3,
            temp_f: 88.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 351,
            wind_dir: "N",
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 48,
            feelslike_c: 32.6,
            feelslike_f: 90.7,
            windchill_c: 31.3,
            windchill_f: 88.3,
            heatindex_c: 32.6,
            heatindex_f: 90.7,
            dewpoint_c: 20.4,
            dewpoint_f: 68.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 7.0
          },
          {
            time_epoch: 1627891200,
            time: "2023-08-02 11:00",
            temp_c: 32.4,
            temp_f: 90.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 359,
            wind_dir: "N",
            pressure_mb: 1010.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 47,
            cloud: 0,
            feelslike_c: 33.9,
            feelslike_f: 93.0,
            windchill_c: 32.4,
            windchill_f: 90.3,
            heatindex_c: 33.9,
            heatindex_f: 93.0,
            dewpoint_c: 19.7,
            dewpoint_f: 67.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 8.0
          },
          {
            time_epoch: 1627894800,
            time: "2023-08-02 12:00",
            temp_c: 33.6,
            temp_f: 92.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 8,
            wind_dir: "N",
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 41,
            cloud: 0,
            feelslike_c: 35.2,
            feelslike_f: 95.4,
            windchill_c: 33.6,
            windchill_f: 92.5,
            heatindex_c: 35.2,
            heatindex_f: 95.4,
            dewpoint_c: 19.0,
            dewpoint_f: 66.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 8.0
          },
          {
            time_epoch: 1627898400,
            time: "2023-08-02 13:00",
            temp_c: 34.4,
            temp_f: 93.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 16,
            wind_dir: "NNE",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 38,
            cloud: 0,
            feelslike_c: 36.1,
            feelslike_f: 97.0,
            windchill_c: 34.4,
            windchill_f: 93.9,
            heatindex_c: 36.1,
            heatindex_f: 97.0,
            dewpoint_c: 18.2,
            dewpoint_f: 64.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 9.0
          },
          {
            time_epoch: 1627902000,
            time: "2023-08-02 14:00",
            temp_c: 34.5,
            temp_f: 94.1,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 25,
            wind_dir: "NNE",
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 38,
            cloud: 32,
            feelslike_c: 36.3,
            feelslike_f: 97.3,
            windchill_c: 34.5,
            windchill_f: 94.1,
            heatindex_c: 36.3,
            heatindex_f: 97.3,
            dewpoint_c: 18.3,
            dewpoint_f: 64.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 9.0
          },
          {
            time_epoch: 1627905600,
            time: "2023-08-02 15:00",
            temp_c: 34.0,
            temp_f: 93.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 33,
            wind_dir: "NNE",
            pressure_mb: 1008.0,
            pressure_in: 29.75,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 42,
            cloud: 65,
            feelslike_c: 36.1,
            feelslike_f: 97.0,
            windchill_c: 34.0,
            windchill_f: 93.2,
            heatindex_c: 36.1,
            heatindex_f: 97.0,
            dewpoint_c: 19.4,
            dewpoint_f: 66.9,
            will_it_rain: 0,
            chance_of_rain: 26,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.0,
            gust_kph: 17.6,
            uv: 9.0
          },
          {
            time_epoch: 1627909200,
            time: "2023-08-02 16:00",
            temp_c: 33.0,
            temp_f: 91.4,
            is_day: 1,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 38,
            wind_dir: "NE",
            pressure_mb: 1008.0,
            pressure_in: 29.76,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 49,
            cloud: 77,
            feelslike_c: 35.4,
            feelslike_f: 95.7,
            windchill_c: 33.0,
            windchill_f: 91.4,
            heatindex_c: 35.4,
            heatindex_f: 95.7,
            dewpoint_c: 21.0,
            dewpoint_f: 69.8,
            will_it_rain: 0,
            chance_of_rain: 53,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 12.1,
            gust_kph: 19.4,
            uv: 9.0
          },
          {
            time_epoch: 1627912800,
            time: "2023-08-02 17:00",
            temp_c: 32.0,
            temp_f: 89.6,
            is_day: 1,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 43,
            wind_dir: "NE",
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 55,
            cloud: 90,
            feelslike_c: 34.8,
            feelslike_f: 94.6,
            windchill_c: 32.0,
            windchill_f: 89.6,
            heatindex_c: 34.8,
            heatindex_f: 94.6,
            dewpoint_c: 22.0,
            dewpoint_f: 71.6,
            will_it_rain: 1,
            chance_of_rain: 79,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 8.0,
            vis_miles: 4.0,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 8.0
          },
          {
            time_epoch: 1627916400,
            time: "2023-08-02 18:00",
            temp_c: 30.8,
            temp_f: 87.4,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 44,
            wind_dir: "NE",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 62,
            cloud: 83,
            feelslike_c: 33.9,
            feelslike_f: 93.0,
            windchill_c: 30.8,
            windchill_f: 87.4,
            heatindex_c: 33.9,
            heatindex_f: 93.0,
            dewpoint_c: 22.8,
            dewpoint_f: 73.0,
            will_it_rain: 1,
            chance_of_rain: 81,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 8.0,
            vis_miles: 4.0,
            gust_mph: 14.3,
            gust_kph: 23.0,
            uv: 7.0
          },
          {
            time_epoch: 1627920000,
            time: "2023-08-02 19:00",
            temp_c: 29.6,
            temp_f: 85.3,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 40,
            wind_dir: "NE",
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 69,
            cloud: 77,
            feelslike_c: 33.0,
            feelslike_f: 91.4,
            windchill_c: 29.6,
            windchill_f: 85.3,
            heatindex_c: 33.0,
            heatindex_f: 91.4,
            dewpoint_c: 23.3,
            dewpoint_f: 73.9,
            will_it_rain: 0,
            chance_of_rain: 61,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 14.3,
            gust_kph: 23.0,
            uv: 1.0
          },
          {
            time_epoch: 1627923600,
            time: "2023-08-02 20:00",
            temp_c: 28.5,
            temp_f: 83.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 36,
            wind_dir: "NE",
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 75,
            cloud: 70,
            feelslike_c: 32.1,
            feelslike_f: 89.8,
            windchill_c: 28.5,
            windchill_f: 83.3,
            heatindex_c: 32.1,
            heatindex_f: 89.8,
            dewpoint_c: 23.8,
            dewpoint_f: 74.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.5,
            gust_kph: 23.4,
            uv: 1.0
          },
          {
            time_epoch: 1627927200,
            time: "2023-08-02 21:00",
            temp_c: 27.5,
            temp_f: 81.5,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 32,
            wind_dir: "NNE",
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 81,
            cloud: 64,
            feelslike_c: 31.2,
            feelslike_f: 88.2,
            windchill_c: 27.5,
            windchill_f: 81.5,
            heatindex_c: 31.2,
            heatindex_f: 88.2,
            dewpoint_c: 24.2,
            dewpoint_f: 75.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.8,
            gust_kph: 23.8,
            uv: 1.0
          },
          {
            time_epoch: 1627930800,
            time: "2023-08-02 22:00",
            temp_c: 27.0,
            temp_f: 80.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 27,
            wind_dir: "NNE",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 84,
            cloud: 44,
            feelslike_c: 30.3,
            feelslike_f: 86.5,
            windchill_c: 27.0,
            windchill_f: 80.6,
            heatindex_c: 30.3,
            heatindex_f: 86.5,
            dewpoint_c: 24.1,
            dewpoint_f: 75.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 1.0
          },
          {
            time_epoch: 1627934400,
            time: "2023-08-02 23:00",
            temp_c: 26.6,
            temp_f: 79.9,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 21,
            wind_dir: "NNE",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 25,
            feelslike_c: 29.4,
            feelslike_f: 84.9,
            windchill_c: 26.6,
            windchill_f: 79.9,
            heatindex_c: 29.4,
            heatindex_f: 84.9,
            dewpoint_c: 24.0,
            dewpoint_f: 75.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
            uv: 1.0
          }
        ]
      },
      {
        date: "2023-08-03",
        date_epoch: 1627948800,
        day: {
          maxtemp_c: 33.3,
          maxtemp_f: 91.9,
          mintemp_c: 26.0,
          mintemp_f: 78.8,
          avgtemp_c: 29.3,
          avgtemp_f: 84.7,
          maxwind_mph: 12.3,
          maxwind_kph: 19.8,
          totalprecip_mm: 0.4,
          totalprecip_in: 0.02,
          totalsnow_cm: 0.0,
          avgvis_km: 9.7,
          avgvis_miles: 6.0,
          avghumidity: 75,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 63,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063
          },
          uv: 7.0
        },
        astro: {
          sunrise: "05:40 AM",
          sunset: "07:02 PM",
          moonrise: "01:32 AM",
          moonset: "03:28 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "25"
        },
        hour: []
      },
      {
        date: "2023-08-04",
        date_epoch: 1628035200,
        day: {
          maxtemp_c: 32.3,
          maxtemp_f: 90.1,
          mintemp_c: 26.1,
          mintemp_f: 79.0,
          avgtemp_c: 28.8,
          avgtemp_f: 83.8,
          maxwind_mph: 10.3,
          maxwind_kph: 16.6,
          totalprecip_mm: 1.6,
          totalprecip_in: 0.06,
          totalsnow_cm: 0.0,
          avgvis_km: 9.0,
          avgvis_miles: 5.0,
          avghumidity: 78,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 87,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063
          },
          uv: 7.0
        },
        astro: {
          sunrise: "05:41 AM",
          sunset: "07:01 PM",
          moonrise: "02:19 AM",
          moonset: "04:19 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "17"
        },
        hour: []
      },
      {
        date: "2023-08-05",
        date_epoch: 1628121600,
        day: {
          maxtemp_c: 32.5,
          maxtemp_f: 90.5,
          mintemp_c: 26.2,
          mintemp_f: 79.2,
          avgtemp_c: 28.8,
          avgtemp_f: 83.8,
          maxwind_mph: 11.9,
          maxwind_kph: 19.1,
          totalprecip_mm: 0.7,
          totalprecip_in: 0.03,
          totalsnow_cm: 0.0,
          avgvis_km: 9.5,
          avgvis_miles: 5.0,
          avghumidity: 77,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 83,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063
          },
          uv: 7.0
        },
        astro: {
          sunrise: "05:41 AM",
          sunset: "07:01 PM",
          moonrise: "03:09 AM",
          moonset: "05:08 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "10"
        },
        hour: []
      },
      {
        date: "2023-08-06",
        date_epoch: 1628208000,
        day: {
          maxtemp_c: 31.2,
          maxtemp_f: 88.2,
          mintemp_c: 25.3,
          mintemp_f: 77.5,
          avgtemp_c: 28.2,
          avgtemp_f: 82.8,
          maxwind_mph: 12.3,
          maxwind_kph: 19.8,
          totalprecip_mm: 3.7,
          totalprecip_in: 0.15,
          totalsnow_cm: 0.0,
          avgvis_km: 8.5,
          avgvis_miles: 5.0,
          avghumidity: 83,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 88,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Moderate rain",
            icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
            code: 1189
          },
          uv: 6.0
        },
        astro: {
          sunrise: "05:42 AM",
          sunset: "07:00 PM",
          moonrise: "04:04 AM",
          moonset: "05:54 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "4"
        },
        hour: []
      },
      {
        date: "2023-08-07",
        date_epoch: 1628294400,
        day: {
          maxtemp_c: 29.5,
          maxtemp_f: 85.1,
          mintemp_c: 24.8,
          mintemp_f: 76.6,
          avgtemp_c: 27.2,
          avgtemp_f: 81.0,
          maxwind_mph: 13.9,
          maxwind_kph: 22.3,
          totalprecip_mm: 8.6,
          totalprecip_in: 0.34,
          totalsnow_cm: 0.0,
          avgvis_km: 8.2,
          avgvis_miles: 5.0,
          avghumidity: 87,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 89,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Heavy rain",
            icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
            code: 1195
          },
          uv: 6.0
        },
        astro: {
          sunrise: "05:42 AM",
          sunset: "06:59 PM",
          moonrise: "05:03 AM",
          moonset: "06:37 PM",
          moon_phase: "New Moon",
          moon_illumination: "0"
        },
        hour: []
      },
      {
        date: "2023-08-08",
        date_epoch: 1628380800,
        day: {
          maxtemp_c: 28.8,
          maxtemp_f: 83.8,
          mintemp_c: 24.7,
          mintemp_f: 76.5,
          avgtemp_c: 26.7,
          avgtemp_f: 80.1,
          maxwind_mph: 14.1,
          maxwind_kph: 22.7,
          totalprecip_mm: 7.3,
          totalprecip_in: 0.29,
          totalsnow_cm: 0.0,
          avgvis_km: 7.9,
          avgvis_miles: 4.0,
          avghumidity: 88,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 89,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Moderate rain",
            icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
            code: 1189
          },
          uv: 5.0
        },
        astro: {
          sunrise: "05:43 AM",
          sunset: "06:58 PM",
          moonrise: "06:04 AM",
          moonset: "07:17 PM",
          moon_phase: "New Moon",
          moon_illumination: "0"
        },
        hour: []
      }
    ]
  },
  alerts: {
    alert: []
  }
};

export const mockNews = [
  {
    source: {
      id: null,
      name: "Dainik Jagran"
    },
    author: "Jagran News Desk",
    title: "Lucknow Makes Progress in Smart City Mission Projects",
    description: "The Lucknow Municipal Corporation has completed several key infrastructure projects under the Smart City Mission, including smart roads, integrated traffic management systems, and public WiFi zones.",
    url: "https://example.com/lucknow-smart-city",
    urlToImage: "https://images.pexels.com/photos/11443711/pexels-photo-11443711.jpeg",
    publishedAt: "2023-08-01T08:30:00Z",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam quis aliquam ultricies, nisl nunc ultricies nisl, nec ultricies nisl nunc vel nisl."
  },
  {
    source: {
      id: null,
      name: "Times of India"
    },
    author: "TOI Staff",
    title: "New Cultural Festival to Celebrate Lucknow's Heritage",
    description: "The Uttar Pradesh Tourism Department announces a month-long cultural festival in Lucknow to showcase the city's rich Nawabi heritage, traditional crafts, and cuisine.",
    url: "https://example.com/lucknow-cultural-festival",
    urlToImage: "https://images.pexels.com/photos/6910242/pexels-photo-6910242.jpeg",
    publishedAt: "2023-07-30T14:15:00Z",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam quis aliquam ultricies, nisl nunc ultricies nisl, nec ultricies nisl nunc vel nisl."
  },
  {
    source: {
      id: null,
      name: "Hindustan Times"
    },
    author: "HT Correspondent",
    title: "Lucknow Airport Expansion Project Gets Approval",
    description: "The Chaudhary Charan Singh International Airport in Lucknow will undergo major expansion with a new terminal building and extended runway to accommodate increased air traffic.",
    url: "https://example.com/lucknow-airport-expansion",
    urlToImage: "https://images.pexels.com/photos/62623/wing-plane-flying-airplane-62623.jpeg",
    publishedAt: "2023-07-28T11:45:00Z",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam quis aliquam ultricies, nisl nunc ultricies nisl, nec ultricies nisl nunc vel nisl."
  },
  {
    source: {
      id: null,
      name: "The Indian Express"
    },
    author: "Express News Service",
    title: "Uttar Pradesh Government Launches Eco-Tourism Initiative",
    description: "The state government has identified several natural sites across Uttar Pradesh, including areas near Lucknow, for eco-tourism development with sustainable practices.",
    url: "https://example.com/up-eco-tourism",
    urlToImage: "https://images.pexels.com/photos/5157272/pexels-photo-5157272.jpeg",
    publishedAt: "2023-07-25T09:20:00Z",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam quis aliquam ultricies, nisl nunc ultricies nisl, nec ultricies nisl nunc vel nisl."
  }
];